### ISSUE TITLE
ToDo для 2 версии

### ISSUE THREAD

**Issue by dobernike** [dobernike/EAextended#1]
Общее:
- Сделать кроссбраузерность на 
- [x] chrome
- [x] firefox
- [x] yandex browser
- [x] opera
- [x] edge
- [x] ie (last)

На странице http://opt.euroauto.ru/?option=com_eaopt&task=invoice
- [x] Вместо **Оплата** написать **Прибыль** , ниже вместо **Оплачено** выводить прибыль / 2.

На странице http://opt.euroauto.ru/?task=invoicePrint&option=com_eaopt&id=*
- [x] Меняем значение **Цена(руб)**  на **ценаЕА - 15% **
- [x] Меняем значение **Сумма(руб)** на **Цена** * на **Количество** 
- [x] Номер накладной заменяем рандом от 10000 до 100000
- [x] Баркод от номера правее
- [x] Проверка на имена более одного слова
- [x] Товары Б/У = **ценаЕА**  до округления 100
- [x] Масло = до округления 100
- [x] Антифриз = до округления 100
